import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/app.css'
import Providers from '@/components/providers'
import { Feedback } from '@/components/FeedbackLogic'
import LanguageDropdown from '@/components/menus/LanguageDropdown'
import LanguageWrapper from '@/components/shells/LanguageWrapper'
import { useTranslation } from 'react-i18next'
import { Header } from '@/components/menus/Header'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className={`${inter.className} bg-body`}>
        <Providers>
          <LanguageWrapper>
            <Header />
            {children}
            <Feedback />
          </LanguageWrapper>
        </Providers>
      </body>
    </html>
  )
}
